"""CONFIG FOR EEG PART"""

EEG_SIGNAL_FRAME_SIZE = 128
EEG_NUM_OF_ELECTRODES = 19
FS = 128

CUTOFFS = [(4,8), (12,30), (4,30)]  # Frequency [theta, beta, both]

CNN_INPUT_SHAPE = (EEG_NUM_OF_ELECTRODES, EEG_SIGNAL_FRAME_SIZE, 1)
CNN_EPOCHS = 5
CNN_BATCH_SIZE = 32
CNN_LEARNING_RATE = 0.001
TEST_SIZE_EEG_CNN = 0.2
MODEL_CNN_NAME = "0.9307"

